<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Umbraco Storage Providers - Common S3 Blob Storage</Title>
    <Authors>AnhNV</Authors>
    <PackageProjectUrl>https://github.com/ngoctubk/Umbraco.StorageProviders.S3</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ngoctubk/Umbraco.StorageProviders.S3</RepositoryUrl>
    <PackageIcon>Logo.png</PackageIcon>
    <PackageTags>umbraco;s3;umbraco-marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\brand\Logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.7" />
    <PackageReference Include="SixLabors.ImageSharp.Web.Providers.AWS" Version="3.2.0" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="16.2.0" />
  </ItemGroup>

</Project>
